//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace DORA.Docent.UserControls {
    
    
    public partial class ucDocentInstellingen {
        
        /// <summary>
        /// ucDocentInstellingenTable control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Table ucDocentInstellingenTable;
        
        /// <summary>
        /// ucDocentInstellingenLblHeader control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ucDocentInstellingenLblHeader;
        
        /// <summary>
        /// ucDocentInstellingenLblBeschrijving control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ucDocentInstellingenLblBeschrijving;
        
        /// <summary>
        /// ucDocentInstellingenLblBeschikbaarheid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ucDocentInstellingenLblBeschikbaarheid;
        
        /// <summary>
        /// ucDocentInstellingenDdlBeschikbaarheid control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ucDocentInstellingenDdlBeschikbaarheid;
        
        /// <summary>
        /// ucDocentInstellingenChkBeschikbaar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.CheckBox ucDocentInstellingenChkBeschikbaar;
        
        /// <summary>
        /// ucDocentInstellingenLblBeschikbaarheidTijdVan control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ucDocentInstellingenLblBeschikbaarheidTijdVan;
        
        /// <summary>
        /// ucDocentInstellingenLblBeschikbaarheidTijdTot control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ucDocentInstellingenLblBeschikbaarheidTijdTot;
        
        /// <summary>
        /// ucDocentInstellingenLblBeschikbaarheidTijd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ucDocentInstellingenLblBeschikbaarheidTijd;
        
        /// <summary>
        /// ucDocentInstellingenDdlBeschikbaarheidTijd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ucDocentInstellingenDdlBeschikbaarheidTijd;
        
        /// <summary>
        /// ucDocentInstellingenBeschikbaarheidTijdTot control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ucDocentInstellingenBeschikbaarheidTijdTot;
        
        /// <summary>
        /// ucDocentInstellingenLblGespreksduur control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ucDocentInstellingenLblGespreksduur;
        
        /// <summary>
        /// ucDocentInstellingenDdlGespreksduur control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ucDocentInstellingenDdlGespreksduur;
        
        /// <summary>
        /// ucDocentInstellingenLblDeadline control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ucDocentInstellingenLblDeadline;
        
        /// <summary>
        /// ucDocentInstellingenDeadlineDatums control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ucDocentInstellingenDeadlineDatums;
        
        /// <summary>
        /// ucDocentInstellingenLblDeadlineTijd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label ucDocentInstellingenLblDeadlineTijd;
        
        /// <summary>
        /// ucDocentInstellingenDeadlineTijd control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList ucDocentInstellingenDeadlineTijd;
        
        /// <summary>
        /// ucDocentInstellingenBtnInstellingenBevestigen control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button ucDocentInstellingenBtnInstellingenBevestigen;
    }
}
